var convict = require('convict');
var validator = require('validator');

var config = convict({
  analytics: {
    googleServiceEmail: {
      doc: 'The google email address generated by developer console',
      default: null,
      format: String,
      env: 'GOOGLE_SERVICE_EMAIL'
    },
    googleServiceKeypath: {
      doc: 'Absolute path to service account .PEM file',
      default: null,
      format: String,
      env: 'GOOGLE_SERVICE_KEYPATH'
    }
  }
});

module.exports = config;