import convict from 'convict';
import validator from 'validator';

const config = convict({
  analytics: {
    googleServiceEmail: {
      doc: 'The google email address generated by developer console',
      default: null,
      format: String,
      env: 'GOOGLE_SERVICE_EMAIL'
    },
    googleServiceKeypath: {
      doc: 'Absolute path to service account .PEM file',
      default: null,
      format: String,
      env: 'GOOGLE_SERVICE_KEYPATH'
    },
    googleServiceKey: {
      doc: 'Contents of the .PEM file. Either key or keypath is required',
      default: null,
      format: String,
      env: 'GOOGLE_SERVICE_KEY'
    }
  }
});

export default config;
